name: Android CI - Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle CLI
        uses: gradle/actions/setup-gradle@v3

      - name: Generate Gradle Wrapper if missing
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "gradlew not found. Generating wrapper..."
            gradle wrapper --gradle-version 8.4
          fi

      - name: Make wrapper executable
        run: chmod +x gradlew

      - name: Restore keystore from secret
        env:
          KEYSTORE_B64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_B64" | base64 --decode > release-keystore.jks

      - name: Write signing properties
        run: |
          cat > keystore.properties <<EOF
          storeFile=release-keystore.jks
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          EOF

      - name: Build Release APK
        run: ./gradlew clean assembleRelease --no-daemon

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/mapping/release/mapping.txt
